export const dataObjects = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    image: 'https://picsum.photos/id/1015/200/300',
    rating: '⭐⭐⭐⭐',
    review: 'A classic novel that addresses important social issues.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    image: 'https://picsum.photos/id/1016/200/300',
    rating: '⭐⭐⭐⭐⭐',
    review: 'A dystopian masterpiece that explores the consequences of totalitarianism.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 3,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    image: 'https://picsum.photos/id/1018/200/300',
    rating: '⭐⭐⭐⭐',
    review: 'An iconic portrayal of teenage angst and rebellion.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 4,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    image: 'https://picsum.photos/id/1019/200/300',
    rating: '⭐⭐⭐',
    review: 'A tale of decadence and the American Dream in the Roaring Twenties.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 5,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    image: 'https://picsum.photos/id/1020/200/300',
    rating: '⭐⭐',
    review: 'An epic tale of obsession and revenge on the high seas.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 6,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    image: 'https://picsum.photos/id/1024/200/300',
    rating: '⭐⭐⭐',
    review: 'A classic romance novel that explores themes of class and society.',
    category: 'Comic',
    language: 'English',
  },
  {
    id: 7,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    image: 'https://picsum.photos/id/1025/200/300',
    rating: '⭐⭐⭐',
    review: 'A fantasy adventure that introduces readers to the world of Middle-earth.',
    category: 'Novel',
    language: 'English',
  },
  {
    id: 8,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    image: 'https://picsum.photos/id/1031/200/300',
    rating: '⭐⭐⭐',
    review: 'A magical realist novel that chronicles the Buendía family in the fictional town of Macondo.',
    category: 'Novel',
    language: 'Spanish',
  },
  {
    id: 9,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    image: 'https://picsum.photos/id/1032/200/300',
    rating: '⭐⭐⭐⭐',
    review: 'An epic high-fantasy trilogy set in the world of Middle-earth.',
    category: 'Comic',
    language: 'English',
  },
  {
    id: 10,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    image: 'https://picsum.photos/id/1033/200/300',
    rating: '⭐⭐',
    review: 'A dystopian novel that explores the dark side of a utopian society.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 11,
    title: 'The Odyssey',
    author: 'Homer',
    image: 'https://picsum.photos/id/1045/200/300',
    rating: '⭐⭐⭐',
    review: 'An ancient Greek epic poem that follows the hero Odysseus on his journey home after the Trojan War.',
    category: 'Comic',
    language: 'Ancient Greek',
  },
  {
    id: 12,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    image: 'https://picsum.photos/id/1035/200/300',
    rating: '⭐',
    review: 'A Gothic novel that tells the story of Victor Frankenstein and his monstrous creation.',
    category: 'Comic',
    language: 'English',
  },
  {
    id: 13,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    image: 'https://picsum.photos/id/1036/200/300',
    rating: '⭐⭐⭐',
    review: 'A passionate tale of love and revenge on the Yorkshire moors.',
    category: 'Fiction',
    language: 'English',
  },
  {
    id: 14,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    image: 'https://picsum.photos/id/1037/200/300',
    rating: '⭐⭐⭐⭐',
    review: 'A psychological thriller that explores the moral dilemmas faced by the protagonist, Raskolnikov.',
    category: 'Novel',
    language: 'Russian',
  },
  {
    id: 15,
    title: 'The Shining',
    author: 'Stephen King',
    image: 'https://picsum.photos/id/1038/200/300',
    rating: '⭐⭐⭐⭐⭐',
    review: 'A horror novel that follows the story of Jack Torrance and his family at the isolated Overlook Hotel.',
    category: 'Comic',
    language: 'English',
  },
  {
    id: 16,
    title: 'Wings of Fire',
    author: 'APJ',
    image: 'https://www.bookspace.in/cdn/shop/products/11_c93f501e-ee35-40d2-a971-0b7c2bac2e0b.jpg?v=1678196081&width=823',
    rating: '⭐⭐⭐⭐',
    review: 'A horror novel that follows the story of Jack Torrance and his family at the isolated Overlook Hotel.',
    category: 'Novel',
    language: 'English',
  }
  ];